# Generated by Django 4.2.3 on 2024-06-10 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=150, null=True)),
                ('nombre_finca', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(max_length=150, null=True)),
                ('telefono', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_lote', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(default='', max_length=150, null=True)),
                ('hectareas', models.FloatField(default=0)),
                ('finca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='Fincas.finca')),
            ],
        ),
        migrations.CreateModel(
            name='InfoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=20)),
                ('numero_documento', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bodegas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default='', max_length=5, null=True)),
                ('nombre_bodega', models.CharField(max_length=150)),
                ('ubicacion', models.CharField(default='', max_length=150, null=True)),
                ('lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='Fincas.lotes')),
                ('usuario', models.ManyToManyField(null=True, related_name='bodegas_finca_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
